In [1]:
import numpy as np

Array Operation

Arithmetic Operation

In [2]:
a1 = np.arange(1,6)
a2 = np.arange(6,11)
a2

array([ 6,  7,  8,  9, 10])

In [3]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [4]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [5]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [6]:
a2 / a1

array([6.        , 3.5       , 2.66666667, 2.25      , 2.        ])

In [7]:
a2 // a1

array([6, 3, 2, 2, 2])

In [8]:
a2 ** a1

array([     6,     49,    512,   6561, 100000])

What is Broadcasting?

In [9]:
l = [1,2,3,4,5]
arr = np.array(l)

In [10]:
l+10

TypeError: can only concatenate list (not "int") to list

In [11]:
arr+10

array([11, 12, 13, 14, 15])

Shallow and Deep Copy

In [14]:
lst = [1,2,3,4,5]
shallow = lst
lst

[1, 2, 3, 4, 5]

In [15]:
shallow[0] = 5
shallow

[5, 2, 3, 4, 5]

In [16]:
lst

[5, 2, 3, 4, 5]

In [27]:
arr = np.arange(1,6)
deep = arr[:3]
arr

array([1, 2, 3, 4, 5])

In [28]:
deep = deep * 2
deep

array([2, 4, 6])

In [29]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
# Array ma bi shallow copy ho jati hai agar element copy kro 
# new_arr =arr
# new_arr[0] = 99
# Dono ma change ho ga

Matrix operation

In [35]:
a1 = np.array([[1,2],[3,4]])
a2 = np.array([[5,6],[7,8]])


In [ ]:
# Matrix Multiplication
a1 @ a2

array([[19, 22],
       [43, 50]])

In [37]:
# Transpose
a2.T

array([[5, 7],
       [6, 8]])

Advance Array Manipulation

Stacking Array

In [39]:
A1 = np.arange(1,6)
A2 = np.arange(6,11)

In [40]:
np.vstack((A1,A2))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [41]:
np.hstack((A1,A2))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
np.column_stack((A1,A2))

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

Splitting Array

In [46]:
A = np.arange(1,17).reshape(4,4)
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [47]:
np.hsplit(A,2)


[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [48]:
np.vsplit(A,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]