In [2]:
import numpy as np

Basic Array Creation

In [4]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [7]:
l2 = [1,2,3,4,5]
l1=np.array(l2)
l1

array([1, 2, 3, 4, 5])

In [13]:
l = [[1,2,3],[1,2,3],[1,2,3]]
l

[[1, 2, 3], [1, 2, 3], [1, 2, 3]]

In [15]:
a=np.array(l)
a

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [17]:
li = [1,2,3,4.5,'Hello']
np.array(li)

array(['1', '2', '3', '4.5', 'Hello'], dtype='<U32')

Array Generation Function

In [20]:
arr = np.arange(1,10,2)
arr

array([1, 3, 5, 7, 9])

In [23]:
arr=np.zeros((6,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
arr = np.ones((4,2))
arr

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [26]:
# linspace important function that is use for equally space between interval like 1 to 5 we want 3 value so it give us 1,3,5
np.linspace(1,5,3)

array([1., 3., 5.])

Random Generation Function

In [28]:
# This function use concept of Normaizaltion always give answer between 0 to 1
np.random.rand(3)

array([0.8292862 , 0.94275283, 0.93725824])

In [30]:
# This function use concept of Normaizaltion always give answer between -3 to 3
np.random.randn(5)

array([ 0.41441625, -0.03017854, -0.10592652, -0.31050267, -0.30794639])

In [32]:
# This function will print only 1 number between 0 to 5
np.random.randint(5)

4

In [34]:
# if we want more random number
np.random.randint(10,20,10)

array([15, 17, 10, 18, 16, 18, 11, 18, 19, 12], dtype=int32)

In [35]:
# If you want unique numbers each time
nums = np.random.choice(np.arange(10, 20), size=10, replace=False)
print(nums)


[14 15 12 11 16 10 19 17 18 13]


Array Method

In [38]:
arr = np.array([[1,2,3],[2,3,4],[3,4,5]])
arr.shape

(3, 3)

In [39]:
arr.size

9

In [40]:
arr.dtype

dtype('int64')

In [43]:
arr.itemsize

8

Array Method

In [45]:
arr = np.array([[1,2,3],[2,3,4],[3,4,5]])
arr.max()

np.int64(5)

In [46]:
arr.min()

np.int64(1)

In [47]:
arr.sum()

np.int64(27)

In [48]:
np.sum(arr,axis=0)

array([ 6,  9, 12])

In [50]:
np.sum(arr,axis=1)

array([ 6,  9, 12])

In [51]:
arr.mean()

np.float64(3.0)

In [52]:
arr.std()

np.float64(1.1547005383792515)

In [53]:
arr.argmax()

np.int64(8)

In [54]:
arr.argmin()

np.int64(0)

Reshaping and Resizing

In [55]:
arr

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [56]:
arr.reshape(9)

array([1, 2, 3, 2, 3, 4, 3, 4, 5])

In [59]:
arr.resize(9)
arr

array([1, 2, 3, 2, 3, 4, 3, 4, 5])