In [1]:
import numpy as np

Check Valid Sudoku

In [15]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [11]:
new_array=np.sum(s,axis=1)


In [12]:
for i in new_array:
  if i != 45:
    print("Sudoku is not valid")
else:
  print("Row Sudoku is Vallid")

Row Sudoku is Vallid


In [13]:
new_array2=np.sum(s,axis=0)
for i in new_array2:
  if i != 45:
    print("Sudoku is not valid")
    break
else:
  print("Columne Sudoku is Vallid")

Columne Sudoku is Vallid


3*3 Block Sum equal to 45

In [42]:
for i in range(0,9,3):
  for j in range(0,9,3):
   n=s[i:i+3,j:j+3]
   print(n.sum())


45
45
45
45
45
45
45
45
45


General Question

In [53]:
# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [ ]:
#Get the shape of the matrix.
data.shape

5

In [17]:
# #Find the average age of students.
# length=len(data)
# n = 0
# for i in range(length):
#   n += data[i][0]

# print(n/length)

# age=data[:,0]
# np.average(age)

print(np.mean(data[:,0]))

18.4


In [19]:
#Extract Math marks of all students.
marks=data[:,1]
print(marks)

[85 92 76 65 90]


In [22]:
#Find the highest Science mark.
# data[:,2].max()
np.max(data[:,2])

np.int64(95)

In [29]:
#Get details of the student who scored more than 90 in Math.
scored_more_than_90=marks > 90
data[scored_more_than_90]


array([[19, 92, 88]])

In [3]:
#Increase Math marks of all students by 5.
data[:,1] += 5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [10]:
#Find how many students are younger than 19.
index=data[:,0] < 19
len(data[index])

3

In [15]:
#Calculate the average marks in each subject (column-wise mean).
# for i in range(1,3):
# 	print(np.mean(data[:,i],axis=0))

np.mean(data[:,1:],axis=0)

array([86.6, 83.2])

In [22]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:,1] >= 80) & (data[:,2] >= 80)]


array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [ ]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [54]:
#Replace all Science marks < 75 with 0.
data[:,2][data[:,2] <= 75 ] = 0

In [55]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])