In [3]:
import numpy as np

Numpy Array Indexing and Slicing of Vector

In [2]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [3]:
arr[4]

np.int64(15)

In [4]:
arr[0:5]

array([11, 12, 13, 14, 15])

In [5]:
arr[1::3]

array([12, 15, 18])

In [10]:
arr[-1]

np.int64(20)

Numpy Array Indexing and Slicing of Matrix

In [4]:
arr=np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [12]:
arr[1][2]

np.int64(8)

In [ ]:
arr[0:2,1:3]
# arr[0:2][1:3]

array([[ 6,  7,  8,  9, 10]])

In [5]:
arr[2:,3:]

array([[14, 15],
       [19, 20],
       [24, 25]])

In [6]:
arr[:,2]

array([ 3,  8, 13, 18, 23])

Boolean Indexing

In [7]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [8]:
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [9]:
arr=arr[bool_index]

In [10]:
arr

array([12, 14, 16, 18, 20])